-- Script was generated by Devart dbForge Studio for MySQL, Version 5.0.50.0
-- Product home page: http://www.devart.com/dbforge/mysql/studio
-- Script date 2015/11/11 17:00:00
-- Server version: 5.5.36-log
-- Client version: 4.1

 

CREATE TABLE qst_user_info(
  userid INT(11) NOT NULL COMMENT '用户id 与user_account 的id字段关联',
  `KEY` VARCHAR(16) NOT NULL,
  KEYVALUE VARCHAR(128) DEFAULT NULL,
  UNIQUE INDEX userid (userid, `KEY`)
)
ENGINE = MYISAM
AVG_ROW_LENGTH = 22
CHARACTER SET utf8
COLLATE utf8_general_ci
COMMENT = '用于用户信息管理';