-- Script was generated by Devart dbForge Studio for MySQL, Version 5.0.50.0
-- Product home page: http://www.devart.com/dbforge/mysql/studio
-- Script date 2015/11/11 17:05:20
-- Server version: 5.5.36-log
-- Client version: 4.1

 

CREATE TABLE qst_user_verify(
  id INT(11) UNSIGNED NOT NULL AUTO_INCREMENT COMMENT '主键',
  code VARCHAR(16) NOT NULL COMMENT '验证码',
  `time` DATETIME NOT NULL COMMENT '认证失效时间',
  repeattime DATETIME DEFAULT NULL COMMENT '重复发送失效时间',
  state TINYINT(4) NOT NULL DEFAULT 0 COMMENT '1验证了 0没有验证',
  type SMALLINT(6) DEFAULT NULL COMMENT '1:邮箱2:手机',
  contact VARCHAR(64) DEFAULT NULL COMMENT '联系方式',
  PRIMARY KEY (id)
)
ENGINE = MYISAM
AUTO_INCREMENT = 322
AVG_ROW_LENGTH = 28
CHARACTER SET utf8
COLLATE utf8_general_ci;