-- Script was generated by Devart dbForge Studio for MySQL, Version 5.0.50.0
-- Product home page: http://www.devart.com/dbforge/mysql/studio
-- Script date 2015/11/12 16:53:35
-- Server version: 5.5.36-log
-- Client version: 4.1



DELIMITER $$

CREATE DEFINER = 'livedb'@'%'
PROCEDURE p_bind(IN  vi_param VARCHAR(1024),
                 OUT vo_data  VARCHAR(1024),
                 OUT vo_res   INT
                 )
lab:
BEGIN
  DECLARE vi_type    TINYINT DEFAULT NULL; -- 1邮箱  2手机
  DECLARE vi_userid  VARCHAR(64) DEFAULT NULL;
  DECLARE vi_contact VARCHAR(64) DEFAULT NULL;
  DECLARE v_count    TINYINT DEFAULT 0;
  DECLARE v_id       TINYINT DEFAULT 0;

  DECLARE v_code     VARCHAR(16) DEFAULT NULL;
  DECLARE v_state    INT DEFAULT NULL;

  DECLARE EXIT HANDLER FOR SQLEXCEPTION
  BEGIN
    SET vo_res = 9999;
  END;

  SET vi_userid = getValue(vi_param, 'userid');
  SET vi_type = getValue(vi_param, 'type');
  SET vi_contact = getValue(vi_param, 'contact');

  #getValue返回的空不是NULL.而是""
  IF vi_userid = '' THEN
    SET vo_res = 1035; #未登录
    LEAVE lab;
  END IF;

  IF (vi_type = "" || vi_contact = "") THEN
    SET vo_res = 1007; #参数错误
    LEAVE lab;
  END IF;

  #根据id查找绑定状态
  SELECT state
  INTO
    v_state
  FROM
    qst_user_bind
  WHERE
    contact = vi_contact
    AND type = vi_type
  ;

  #已经绑定过
  IF (v_state = 1) THEN
    SET vo_res = 1005;
    LEAVE lab;
  END IF;

  -- 查询用户是否绑定过同类型的帐号
  SELECT count(*)
       , id
  INTO
    v_count, v_id
  FROM
    qst_user_bind
  WHERE
    userid = vi_userid
    AND type = vi_type
    AND state = 1;

  -- 当前用户绑定过同类型的帐号，置帐号无效，
  IF v_count > 0 THEN
    UPDATE qst_user_bind
    SET
      state = 0
    WHERE
      id = v_id;
  END IF;
  -- 插入新的绑定帐号
  INSERT INTO qst_user_bind (userid, type, contact, state, btime) VALUES (vi_userid, vi_type, vi_contact, 1, now());

  SET vo_data = '';
  SET vo_res = 0;
END
$$

DELIMITER ;