-- Script was generated by Devart dbForge Studio for MySQL, Version 5.0.50.0
-- Product home page: http://www.devart.com/dbforge/mysql/studio
-- Script date 2015/11/11 17:06:34
-- Server version: 5.5.36-log
-- Client version: 4.1

 

DELIMITER $$

CREATE DEFINER = 'livedb'@'%'
PROCEDURE p_check_code(IN  vi_param VARCHAR(1024),
                       OUT vo_data  VARCHAR(1024),
                       OUT vo_res   INT
                       )
lab:
BEGIN
  DECLARE vi_code    VARCHAR(16) DEFAULT NULL;
  DECLARE vi_type    TINYINT DEFAULT NULL;
  DECLARE vi_contact VARCHAR(64) DEFAULT NULL;

  DECLARE v_code     VARCHAR(16) DEFAULT NULL;
  DECLARE v_state    INT DEFAULT NULL;

  DECLARE EXIT HANDLER FOR SQLEXCEPTION
  BEGIN
    SET vo_res = 9999;
  END;

  SET vi_type = getValue(vi_param, 'type');
  SET vi_contact = getValue(vi_param, 'contact');
  SET vi_code = getValue(vi_param, 'code');

  IF (vi_code IS NULL OR vi_type IS NULL OR vi_contact IS NULL) THEN
    SET vo_res = 1007; #参数错误
    LEAVE lab;
  END IF;

  #根据id查找验证码
  SELECT code
  INTO
    v_code
  FROM
    qst_user_verify
  WHERE
    type = vi_type
    AND contact = vi_contact
    AND `time` > now()
    AND state = 0;



  #判断验证码是否一致
  IF (v_code IS NULL || v_code <> vi_code) THEN
    SET vo_res = 1003;
    LEAVE lab;
  END IF;

  UPDATE qst_user_verify
  SET
    state = 1
  WHERE
    type = vi_type
    AND contact = vi_contact
    AND `time` > now()
    AND state = 0;

  SET vo_data = "";
  SET vo_res = 0;
END
$$

DELIMITER ;