-- Script was generated by Devart dbForge Studio for MySQL, Version 5.0.50.0
-- Product home page: http://www.devart.com/dbforge/mysql/studio
-- Script date 2015/11/20 15:59:53
-- Server version: 5.5.36-log
-- Client version: 4.1



DELIMITER $$

CREATE DEFINER = 'livedb'@'%'
PROCEDURE p_modifypwd(IN  vi_param VARCHAR(1024),
                      OUT vo_data  VARCHAR(1024),
                      OUT vo_res   INT
                      )
lab:
BEGIN
  DECLARE vi_userid     VARCHAR(64) DEFAULT NULL;
  DECLARE vi_old_passwd VARCHAR(32) DEFAULT NULL;
  DECLARE vi_new_passwd VARCHAR(32) DEFAULT NULL;

  DECLARE v_passwd      VARCHAR(32) DEFAULT NULL;
  DECLARE EXIT HANDLER FOR SQLEXCEPTION
  BEGIN
    SET vo_res = 9999;
  END;

  SET vi_userid = getValue(vi_param, 'userid');
  SET vi_new_passwd = getValue(vi_param, 'new_passwd');
  SET vi_old_passwd = getValue(vi_param, 'old_passwd');

  IF (vi_userid = "" OR vi_new_passwd = "" OR vi_old_passwd = "") THEN
    SET vo_res = 1007; #²ÎÊý´íÎó
    LEAVE lab;
  END IF;

  SELECT passwd
  INTO
    v_passwd
  FROM
    qst_user
  WHERE
    userid = vi_userid
    AND status = 1;

  IF (v_passwd <> vi_old_passwd) THEN
    SET vo_res = 1008; -- ÃÜÂë´íÎó
    LEAVE lab;
  END IF;

  UPDATE qst_user
  SET
    passwd = vi_new_passwd
  WHERE
    userid = vi_userid
    AND status = 1;

  IF (ROW_COUNT() <= 0) THEN
    SET vo_res = 1001; -- ÕÊºÅ²»´æÔÚ
  END IF;

  SET vo_data = '';
  SET vo_res = 0;
END
$$

DELIMITER ;