-- Script was generated by Devart dbForge Studio for MySQL, Version 5.0.50.0
-- Product home page: http://www.devart.com/dbforge/mysql/studio
-- Script date 2015/11/11 17:10:07
-- Server version: 5.5.36-log
-- Client version: 4.1

 

DELIMITER $$

CREATE DEFINER = 'root'@'%'
PROCEDURE p_other_login(IN  vi_param VARCHAR(1024),
                        OUT vo_data  VARCHAR(1024),
                        OUT vo_res   INT
                        )
lab:
BEGIN
  #access_token~DE89B12F418C136D96F62898CBC4705E,openid~B8C02925F80EE3B4462B86E7868DAC1D,inter_num~1000
  DECLARE vi_access_token VARCHAR(32) DEFAULT NULL;
  DECLARE vi_openid       VARCHAR(32) DEFAULT NULL;
  DECLARE vi_nick         VARCHAR(64) DEFAULT NULL;
  DECLARE vi_typename     VARCHAR(64) DEFAULT NULL;
  DECLARE vi_type         INT DEFAULT 0;
  DECLARE vi_login_type   INT DEFAULT 0; -- 绑定方式 1登录  2绑定
  DECLARE v_headpic       VARCHAR(128) DEFAULT NULL; #头像
  DECLARE v_emailnum      INT DEFAULT 0; #站内信
  DECLARE v_shopcartnum   INT DEFAULT 0; #购物车数据

  DECLARE v_tmpvalue      VARCHAR(128) DEFAULT NULL; #

  DECLARE v_userid        INT DEFAULT 0;
  DECLARE v_id            INT DEFAULT 0;
  DECLARE v_bindid        INT DEFAULT 0;
  DECLARE v_vstatus       INT DEFAULT 0;
  DECLARE v_count         INT DEFAULT 0;
  DECLARE v_params        VARCHAR(1024) DEFAULT '';
  DECLARE EXIT HANDLER FOR SQLEXCEPTION
  BEGIN
    SET vo_res = 9999;
  END;

  SET vi_access_token = getValue(vi_param, 'access_token');
  SET vi_openid = getValue(vi_param, 'openid');
  SET vi_nick = getValue(vi_param, 'nick');
  SET vi_type = getValue(vi_param, 'type'); #1:qq2:微信3:微博
  # SET vi_login_type = getValue(vi_param, 'login_type'); #1:qq2:微信3:微博


  IF (vi_access_token = "" OR vi_openid = "" /*OR vi_nick = ""*/) THEN
    SET vo_res = 1007; #参数错误
    LEAVE lab;
  END IF;

  SELECT count(*)
  INTO
    v_count
  FROM
    qst_user_bind
  WHERE
    openid = vi_openid
    AND type = vi_type
    AND state = 1;

  #SELECT v_count;

  IF v_count = 0 THEN
    SELECT count(*)
    INTO
      v_count
    FROM
      qst_user_bind
    WHERE
      openid = vi_openid
      AND type = vi_type;
    #SELECT v_count;
    IF v_count = 0 THEN
      INSERT INTO qst_user_bind (openid, accesstoken, type, state, btime, nick) VALUES (vi_openid, vi_access_token, vi_type, 1, now(), vi_nick);
      SELECT @@IDENTITY
      INTO
        v_bindid;
      INSERT INTO qst_user (`status`, `time`) VALUES (1, now());
      SELECT @@IDENTITY
      INTO
        v_id;

      SET v_userid = v_id + 100000000;

      UPDATE qst_user
      SET
        userid = vo_userid
      WHERE
        id = v_id;
      UPDATE qst_user_verify
      SET
        userid = v_userid
      WHERE
        id = v_bindid;
    ELSE
      UPDATE qst_user_bind
      SET
        b_time = now(), nick = vi_nick, state = 1
      WHERE
        openid = vi_openid
        AND type = vi_type;
    END IF;
  ELSE
    SELECT userid
         , state
    INTO
      v_userid, v_vstatus
    FROM
      qst_user_bind
    WHERE
      openid = vi_openid
      AND type = vi_type
      AND state = 1;
    IF (v_vstatus = 0) THEN
      SET v_userid = 0;
    END IF;
  END IF;



  SET v_params = addFmtString(v_params, '=', 'userid', v_userid);
  #SET v_params = addFmtString(v_params, '=', 'headpic', v_headpic);
  # SET v_params = addFmtString(v_params, '=', 'emailnum', v_emailnum);
  #SET v_params = addFmtString(v_params, '=', 'shopcartnum', v_shopcartnum);
  SET v_params = concat(v_params, ',', @data);
  SET vo_data = v_params;
  SET vo_res = 0;
END
$$

DELIMITER ;