-- Script was generated by Devart dbForge Studio for MySQL, Version 5.0.50.0
-- Product home page: http://www.devart.com/dbforge/mysql/studio
-- Script date 2015/11/13 14:58:47
-- Server version: 5.5.36-log
-- Client version: 4.1

 

DELIMITER $$

CREATE DEFINER = 'livedb'@'%'
PROCEDURE p_get_order(IN  vi_param VARCHAR(1024),
                      OUT vo_data  VARCHAR(1024),
                      OUT vo_res   INT
                      )
lab:
BEGIN
  DECLARE v_id       INT DEFAULT 0;
  DECLARE vi_type    INT DEFAULT 0;
  DECLARE v_ordernum VARCHAR(64) DEFAULT NULL;
  DECLARE v_param    VARCHAR(1024) DEFAULT '';

  DECLARE EXIT HANDLER FOR SQLEXCEPTION
  BEGIN
    SET vo_res = 9999;
  END;

  SET vi_type = getValue(vi_param, 'type');

  #getValue返回的空不是NULL.而是""
  IF (vi_type = "") THEN
    SET vo_res = 1007; #参数错误
    LEAVE lab;
  END IF;

  INSERT INTO qst_order_code (ordernum, type, state) VALUES (0, vi_type, 0);

  SELECT @@IDENTITY
  INTO
    v_id;

  SELECT concat(v_id, unix_timestamp())
  INTO
    v_ordernum;

  UPDATE qst_order_code
  SET
    ordernum = v_ordernum
  WHERE
    id = v_id;


  SELECT v_ordernum AS ordernum;

  SET vo_data = '';
  SET vo_res = 0;
END
$$

DELIMITER ;