-- Script was generated by Devart dbForge Studio for MySQL, Version 5.0.50.0
-- Product home page: http://www.devart.com/dbforge/mysql/studio
-- Script date 2015/11/12 16:55:34
-- Server version: 5.5.36-log
-- Client version: 4.1



DELIMITER $$

CREATE DEFINER = 'livedb'@'%'
PROCEDURE p_general_code_getpd(IN  vi_param VARCHAR(1024),
                               OUT vo_data  VARCHAR(1024),
                               OUT vo_res   INT
                               )
lab:
BEGIN
  DECLARE vi_code         VARCHAR(16) DEFAULT NULL;
  DECLARE vi_type         VARCHAR(4) DEFAULT NULL;
  DECLARE vi_time         DATETIME;
  DECLARE vi_contact      VARCHAR(64) DEFAULT NULL;

  DECLARE v_id            INT DEFAULT 0;
  DECLARE v_param         VARCHAR(1024) DEFAULT '';
  DECLARE v_count         INT DEFAULT 0;
  DECLARE v_length        INT DEFAULT 0;
  DECLARE v_deadminutes   INT DEFAULT 0;
  DECLARE v_repeatminutes INT DEFAULT 0;
  DECLARE v_repeattime    DATETIME;
  DECLARE EXIT HANDLER FOR SQLEXCEPTION
  BEGIN
    SET vo_res = 9999;
  END;

  SET vi_type = getValue(vi_param, 'type');
  SET vi_contact = getValue(vi_param, 'contact');
  SET v_length = getValue(vi_param, 'length');
  SET v_deadminutes = getValue(vi_param, 'deadminutes');
  SET v_repeatminutes = getValue(vi_param, 'repeatminutes');
  IF !v_length THEN
    SET v_length = 6;
  END IF;
  IF !v_deadminutes THEN
    IF vi_type = '1' THEN
      SET v_deadminutes = 24 * 60; -- 默认一天
    ELSE
      SET v_deadminutes = 30; -- 默认半小时
    END IF;
  END IF;
  IF !v_repeatminutes THEN
    SET v_repeatminutes = 3;
  END IF;

  SET vi_code = getRand(v_length);

  IF (vi_code = "" OR vi_type = "") THEN
    SET vo_res = 1007; #参数错误
    LEAVE lab;
  END IF;

  -- 查找是否有未失效的验证码
  SELECT count(*)
       , id
  INTO
    v_count, v_id
  FROM
    qst_user_verify
  WHERE
    type = vi_type
    AND contact = vi_contact
    AND repeattime > now()
    AND state = 0;

  -- 禁止重发，查出剩余时间
  IF (v_count > 0) THEN
    SET vo_res = 1002;
    SELECT timestampdiff(SECOND, now(), repeattime) AS leftsecond
    FROM
      qst_user_verify
    WHERE
      id = v_id;
    LEAVE lab;
  END IF;

  IF (vi_type = '1') THEN
    SET vi_time = date_add(now(), INTERVAL v_deadminutes MINUTE); -- 邮件的验证码有效期为1天
    SET v_repeattime = date_add(now(), INTERVAL v_repeatminutes MINUTE); -- 手机的验证码重发有效期
  ELSE
    SET vi_time = date_add(now(), INTERVAL v_deadminutes MINUTE); -- 手机的验证码有效期为1分钟
    SET v_repeattime = date_add(now(), INTERVAL v_repeatminutes MINUTE); -- 手机的验证码重发有效期
  END IF;

  -- 置过期验证码为无效
  UPDATE qst_user_verify
  SET
    state = 1
  WHERE
    type = vi_type
    AND contact = vi_contact
    AND state = 0;
  INSERT INTO qst_user_verify (code, `time`, state, type, contact, repeattime) VALUES (vi_code, vi_time, 0, vi_type, vi_contact, v_repeattime);
  SELECT @@IDENTITY
  INTO
    v_id;

  SELECT vi_code AS code
       , v_deadminutes AS deadminutes;

  SET vo_data = '';
  SET vo_res = 0;
END
$$

DELIMITER ;