-- Script was generated by Devart dbForge Studio for MySQL, Version 5.0.50.0
-- Product home page: http://www.devart.com/dbforge/mysql/studio
-- Script date 2015/11/12 16:55:20
-- Server version: 5.5.36-log
-- Client version: 4.1

USE qstdb;

DELIMITER $$

CREATE DEFINER = 'livedb'@'%'
PROCEDURE p_is_bind(IN  vi_param VARCHAR(1024),
                    OUT vo_data  VARCHAR(1024),
                    OUT vo_res   INT
                    )
lab:
BEGIN
  DECLARE vi_type    TINYINT DEFAULT ''; -- 1邮箱  2手机
  DECLARE vi_userid  VARCHAR(32) DEFAULT '';
  DECLARE vi_contact VARCHAR(64) DEFAULT '';

  DECLARE v_code     VARCHAR(16) DEFAULT '';
  DECLARE v_state    INT DEFAULT '';

  DECLARE EXIT HANDLER FOR SQLEXCEPTION
  BEGIN
    SET vo_res = 9999;
  END;

  #SET vi_userid = getValue(vi_param, 'userid');
  SET vi_type = getValue(vi_param, 'type');
  SET vi_contact = getValue(vi_param, 'contact');

  #getValue返回的空不是NULL.而是""
  IF (vi_type = "" || vi_contact = "") THEN
    SET vo_res = 1007; #参数错误
    LEAVE lab;
  END IF;

  #根据id查找绑定状态
  SELECT state
  INTO
    v_state
  FROM
    qst_user_bind
  WHERE
    #userid = vi_userid AND 

    type = vi_type
    AND contact = vi_contact;

  #已经绑定过
  IF (v_state <> 1) THEN
    SET vo_res = 1004; -- 您的联系方式未绑定
    LEAVE lab;
  END IF;

  SET vo_data = '';
  SET vo_res = 0;
END
$$

DELIMITER ;