-- Script was generated by Devart dbForge Studio for MySQL, Version 5.0.50.0
-- Product home page: http://www.devart.com/dbforge/mysql/studio
-- Script date 2015/11/20 16:00:50
-- Server version: 5.5.36-log
-- Client version: 4.1



DELIMITER $$

CREATE DEFINER = 'livedb'@'%'
PROCEDURE p_login(IN  vi_param VARCHAR(1024),
                  OUT vo_data  VARCHAR(1024),
                  OUT vo_res   INT
                  )
lab_proc:
BEGIN
  DECLARE vi_account VARCHAR(255) DEFAULT '';
  DECLARE vi_passwd  VARCHAR(64) DEFAULT ''; -- js端已经加密了
  DECLARE vi_key     VARCHAR(255) DEFAULT '';

  DECLARE v_count    INT DEFAULT 0;
  DECLARE v_userid   INT DEFAULT 0;
  DECLARE v_passwd   VARCHAR(255) DEFAULT '';
  DECLARE v_i        INT DEFAULT 1;
  DECLARE v_len      INT DEFAULT 0;
  DECLARE v_key      VARCHAR(255) DEFAULT NULL;
  DECLARE v_value    VARCHAR(255) DEFAULT '';
  DECLARE v_param    VARCHAR(1024) DEFAULT '';

  DECLARE EXIT HANDLER FOR SQLEXCEPTION
  BEGIN
    SET vo_res = 9999;
  END;

  SET vi_account = getValue(vi_param, 'account');
  SET vi_passwd = getValue(vi_param, 'passwd');
  SET vi_key = getValue(vi_param, 'key');


  SELECT userid
       , passwd
  INTO
    v_userid, v_passwd
  FROM
    qst_user
  WHERE
    account = vi_account
    AND status = 1;

  IF v_passwd != vi_passwd THEN
    SELECT qu.userid
         , qu.passwd
    INTO
      v_userid, v_passwd
    FROM
      qst_user qu
    LEFT JOIN qst_user_bind qub
    ON qu.userid = qub.userid
    WHERE
      qub.contact = vi_account
      AND qub.state = 1;

    IF v_passwd = '' THEN
      SET vo_res = 1001;
      LEAVE lab_proc;
    END IF;
    IF (v_passwd <> vi_passwd) THEN
      SET vo_res = 1008;
      LEAVE lab_proc;
    END IF;

  END IF;

  #返回用户的信息
  SET
  v_count = func_split_TotalLength(vi_key, '+'); #键的个数
  WHILE (v_i <= v_count)
  DO
    SET v_key = func_split(vi_key, '+', v_i); #a=b

    #查找user_info表中的数据
    SELECT KEYVALUE
    INTO
      v_value
    FROM
      qst_user_info
    WHERE
      userid = v_userid
      AND `KEY` = v_key;

    SET v_param = addFmtString(v_param, '=', v_key, v_value);
    SET v_i = v_i + 1;
  END WHILE;



  SET v_param = addFmtString(v_param, '=', 'userid', v_userid);
  SET vo_data = concat(if(vo_data != '', concat(vo_data, ','), ''), v_param);
  SET vo_res = 0;

END
$$

DELIMITER ;