-- Script was generated by Devart dbForge Studio for MySQL, Version 5.0.50.0
-- Product home page: http://www.devart.com/dbforge/mysql/studio
-- Script date 2015/11/20 16:00:10
-- Server version: 5.5.36-log
-- Client version: 4.1



DELIMITER $$

CREATE DEFINER = 'livedb'@'%'
PROCEDURE p_set_newpwd(IN  vi_param VARCHAR(1024),
                       OUT vo_data  VARCHAR(1024),
                       OUT vo_res   INT
                       )
COMMENT '找回密码--设置新密码'
lab:
BEGIN
  DECLARE v_userid   INT DEFAULT 0;
  DECLARE vi_contact VARCHAR(64) DEFAULT NULL;
  DECLARE vi_passwd  VARCHAR(32) DEFAULT NULL;
  DECLARE vi_type    VARCHAR(16) DEFAULT NULL;

  DECLARE EXIT HANDLER FOR SQLEXCEPTION
  BEGIN
    SET vo_res = 9999;
  END;

  SET vi_contact = getValue(vi_param, 'contact');
  SET vi_passwd = getValue(vi_param, 'passwd');
  SET vi_type = getValue(vi_param, 'type');

  IF (vi_contact = "" OR vi_passwd = "") THEN
    SET vo_res = 1007; #参数错误
    LEAVE lab;
  END IF;
  -- 密码加密
  SET vi_passwd = vi_passwd;



  -- 查找用户的userid
  SELECT userid
  INTO
    v_userid
  FROM
    qst_user_bind
  WHERE
    contact = vi_contact
    AND state = 1
    AND type = vi_type;

  -- 更新密码
  UPDATE qst_user
  SET
    passwd = vi_passwd
  WHERE
    userid = v_userid
    AND status = 1;

  IF (ROW_COUNT() <= 0) THEN
    SET vo_res = 1001; -- 帐号不存在
  END IF;

  SET vo_data = '';
  SET vo_res = 0;
END
$$

DELIMITER ;