-- Script was generated by Devart dbForge Studio for MySQL, Version 5.0.50.0
-- Product home page: http://www.devart.com/dbforge/mysql/studio
-- Script date 2015/11/13 15:03:48
-- Server version: 5.5.36-log
-- Client version: 4.1
 

DELIMITER $$

CREATE DEFINER = 'livedb'@'%'
PROCEDURE p_update_order_ios(IN  vi_param VARCHAR(1024),
                             OUT vo_data  VARCHAR(1024),
                             OUT vo_res   INT
                             )
lab:
BEGIN
  DECLARE vi_state    INT DEFAULT 0;
  DECLARE vi_ordernum VARCHAR(64) DEFAULT NULL;

  DECLARE EXIT HANDLER FOR SQLEXCEPTION
  BEGIN
    SET vo_res = 9999;
  END;

  SET vi_state = getValue(vi_param, 'state');
  SET vi_ordernum = getValue(vi_param, 'ordernum');
  #getValue返回的空不是NULL.而是""
  IF (vi_state = "" || vi_ordernum = "") THEN
    SET vo_res = 1007; #参数错误
    LEAVE lab;
  END IF;

  UPDATE qst_order_code
  SET
    state = vi_state
  WHERE
    ordernum = vi_ordernum;

  IF (ROW_COUNT() <= 0) THEN
    SET vo_res = 1009; #更新失败
    LEAVE lab;
  END IF;

  SET vo_data = '';
  SET vo_res = 0;
END
$$

DELIMITER ;