-- Script was generated by Devart dbForge Studio for MySQL, Version 5.0.50.0
-- Product home page: http://www.devart.com/dbforge/mysql/studio
-- Script date 2015/11/20 16:01:13
-- Server version: 5.5.36-log
-- Client version: 4.1



CREATE TABLE qst_user(
  id INT(11) NOT NULL AUTO_INCREMENT,
  userid BIGINT(11) DEFAULT NULL COMMENT '系统内部使用',
  account VARCHAR(64) DEFAULT NULL COMMENT '用户帐号，由用户注册时输入,用户用户登录使用',
  passwd VARCHAR(64) DEFAULT NULL COMMENT '密码',
  del_email VARCHAR(64) DEFAULT NULL COMMENT '邮箱',
  del_tel VARCHAR(20) DEFAULT NULL COMMENT '手机号码',
  del_type SMALLINT(6) NOT NULL DEFAULT 0 COMMENT '0系统用户 1，QQ用户，2微信',
  status INT(11) NOT NULL DEFAULT 1 COMMENT '1记录有效,0 记录无效',
  `time` DATETIME NOT NULL COMMENT '注册时间',
  PRIMARY KEY (id),
  UNIQUE INDEX account (account),
  UNIQUE INDEX PK_USERBASIC (userid)
)
ENGINE = INNODB
AUTO_INCREMENT = 55
AVG_ROW_LENGTH = 8192
CHARACTER SET utf8
COLLATE utf8_general_ci
COMMENT = '用于用户注册登录管理';