-- Script was generated by Devart dbForge Studio for MySQL, Version 5.0.50.0
-- Product home page: http://www.devart.com/dbforge/mysql/studio
-- Script date 2015/11/13 14:58:22
-- Server version: 5.5.36-log
-- Client version: 4.1

 

CREATE TABLE qst_order_code(
  id INT(11) NOT NULL AUTO_INCREMENT,
  ordernum CHAR(64) DEFAULT NULL COMMENT '订单号',
  type INT(11) DEFAULT NULL COMMENT '支付类型',
  state INT(11) DEFAULT NULL COMMENT '支付状态',
  UNIQUE INDEX id (id),
  UNIQUE INDEX ordernum (ordernum)
)
ENGINE = MYISAM
AUTO_INCREMENT = 28
AVG_ROW_LENGTH = 205
CHARACTER SET utf8
COLLATE utf8_general_ci;