-- Script was generated by Devart dbForge Studio for MySQL, Version 5.0.50.0
-- Product home page: http://www.devart.com/dbforge/mysql/studio
-- Script date 2015/11/12 16:56:04
-- Server version: 5.5.36-log
-- Client version: 4.1



CREATE TABLE qst_user_bind(
  id INT(11) NOT NULL AUTO_INCREMENT,
  userid INT(11) NOT NULL COMMENT '用户userid，与qst_user中的userid对应，唯一标识一个用户',
  openid VARCHAR(128) DEFAULT NULL COMMENT '绑定账号  openid',
  accesstoken VARCHAR(128) DEFAULT NULL COMMENT '绑定账号的accesstoken',
  contact VARCHAR(64) DEFAULT NULL COMMENT '联系方式，邮箱或者是手机号',
  nick VARCHAR(64) DEFAULT NULL COMMENT '昵称，第三方绑定时需要',
  btime DATETIME DEFAULT NULL COMMENT '绑定时间',
  type TINYINT(4) NOT NULL DEFAULT 0 COMMENT '绑定类型 1:邮箱绑定2:手机绑定 3QQ 4微信  5微博',
  state TINYINT(4) NOT NULL DEFAULT 0 COMMENT '是否绑定 0:未绑定取消绑定、  1:绑定 绑定状态',
  PRIMARY KEY (id),
  UNIQUE INDEX UK_qst_user_bind (userid, type, state)
)
ENGINE = MYISAM
AUTO_INCREMENT = 28
AVG_ROW_LENGTH = 46
CHARACTER SET utf8
COLLATE utf8_general_ci;